### ISSUE TITLE
[feature request] imagesLoaded

### ISSUE THREAD

**Issue by reilldesign** [hikir1/ImgJust#2]
currently all images are loaded and displayed with 100% before they are brought into the justified layout. some kind of imagesLoaded function would be great which shows the images only in the layout once they are all loaded.

**Comment by hikir1** [comment]
The `reload()` method now sets `style.display` to `block` only after all the images have been resized. The `addImages()` method sets the initial display to `none` to hide them until `reload()` is done. Both of these are called by the constructor. You should still use CSS to set `display` to `none`, as there could still be a noticeable delay until the code is loaded.
